##########################################
# STATUS BAR
set  -g status-attr bright
set  -g status-fg black
set  -g status-bg white

set -g mouse on

# Gotta make a status line more useful
# - show the list of windows with their names (not pane titles, as these are hard to change manually)
# - show session name (since I want to use them more)
# - show some locally useful info (e.g. uptime)
# - pane titles are useful when working remotely (which is almost always), so
set  -g status-left-length  20
set  -g status-left '#[fg=black]#[bg=green] #S #[default] '
set  -g status-right '#[fg=black]#[bg=green][up #(uptime -p | sed -e "s/[^0-9dmh,]//g" -e "s/,/:/g")]#[default]'
set  -g status-justify left

setw -g window-status-format '#[fg=white]#[bg=blue] #I#F #[default]#W'
setw -g window-status-current-format '#[fg=white]#[bg=red] #I#F #W#[default]'

set  -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
# Default name for new windows
setw -g automatic-rename-format 'local'

##########################################
# TERMINAL EMULATOR TITLES
# This section sets the title of the terminal window
set -g set-titles on
set -g set-titles-string "Session '#S': [#I] #W (tmux)"

##########################################
# DEFINE BETTER KEY BINDINGS
unbind C-b
set -g prefix C-j

# double-prefix returns to last window
bind C-j last-window

# " = show list of sessions and windows to switch to
unbind '"'
bind '"' choose-tree -u

# | = horizontal  split
unbind %
bind | split-window -h

# - = vertical split
bind - split-window -v

# Better clipboard support
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# 'y' in copy mode = copy selection to system clipboard
bind-key -t vi-copy y copy-pipe "parcellite"
bind-key y run-shell "tmux save-buffer - | parcellite"

##########################################
# BASIC CONFIG
setw -g mode-keys vi
setw -g alternate-screen on
set-window-option -g window-status-current-bg red

# Set default command to "bash", so that the shell in new window is *NOT* a login shell
set -g default-command "bash"

# Allow xterm titles in terminal window, terminal scrolling with scrollbar, and setting overrides of C-Up, C-Down, C-Left, C-Right
set -g terminal-overrides "rxvt*:XT:smcup@:rmcup@:kUP5=\eOA:kDN5=\eOB:kLFT5=\eOD:kRIT5=\eOC"


#########################################
# TPM (Tmux Plugin Manager) settings
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
