##########################################
# STATUS BAR
set  -g status-utf8 on
set  -g status-keys vi
set  -g status-interval 3
set  -g status-attr bright
set  -g status-fg black
set  -g status-bg white
set  -g display-time 3000

# Gotta make a status line more useful
# - show the list of windows with their names (not pane titles, as these are hard to change manually)
# - show session name (since I want to use them more)
# - show some locally useful info (e.g. uptime)
# - pane titles are useful when working remotely (which is almost always), so
set  -g status-left-length  20
set  -g status-left '#[fg=black]#[bg=green][Session: #S]#[default] '
set  -g status-right '#[fg=black]#[bg=green][up #(uptime -p | sed -e "s/[^0-9dmh,]//g" -e "s/,/:/g")]#[default]'
set  -g status-justify left

setw -g window-status-format '#[fg=white]#[bg=blue] #I#F #[default]#W'
setw -g window-status-current-format '#[fg=white]#[bg=red] #I#F #[fg=black]#[bg=yellow]#W#[default]'

set  -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
# Default name for new windows
setw -g automatic-rename-format 'local'

##########################################
# TERMINAL EMULATOR TITLES
# This section sets the title of the terminal window
set -g set-titles on
set -g set-titles-string "Session '#S': [#I] #W (tmux)"

##########################################
# DEFINE BETTER KEY BINDINGS
# ` (backtick, usually above tab key) = prefix
unbind C-b
set -g prefix C-j
#set -g prefix `
#bind ` send-prefix
bind C-j last-window

unbind '"'
bind '"' choose-window
bind t rename-window local
bind R source ~/.tmux.conf \; display "Cofiguration reloaded!"

# Esc = copy-mode
unbind [
bind [ copy-mode

# | = horizontal  split
unbind %
bind | split-window -h

# - = vertical split
bind - split-window -v

# Copy to system clipboard
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "parcellite"
bind-key y run-shell "tmux save-buffer - | parcellite"

# Move around panes vim style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# bind-key L last-window

# h = display cheatsheet
# bind h run "grep -v '^#' ~/dotfiles/tmux.cheatsheet | column -t -s'|'"

# Toggle mouse on with <prefix>-M
bind M \
  set -g mode-mouse on \;\
  set -g mouse-resize-pane on \;\
  set -g mouse-select-pane on \;\
  set -g mouse-select-window on \;\
  display 'Mouse: ON'

# Toggle mouse off with <prefix>-m
bind m \
  set -g mode-mouse off \;\
  set -g mouse-resize-pane off \;\
  set -g mouse-select-pane off \;\
  set -g mouse-select-window off \;\
  display 'Mouse: OFF'
#
##########################################
# BASIC CONFIG
setw -g utf8 on
setw -g mode-keys vi
setw -g mode-mouse off
setw -g alternate-screen on
setw -g aggressive-resize on
set-window-option -g window-status-current-bg red
set -g mouse-select-pane off
set -g default-terminal "screen-256color"
set -g history-limit 30000

# Lower escape timing from 500ms to 50ms for quicker response to scroll-buffer access.
set -s escape-time 50

# Set default command to "bash", so that the shell in new window is *NOT* a login shell
set -g default-command "bash"

# Allow xterm titles in terminal window, terminal scrolling with scrollbar, and setting overrides of C-Up, C-Down, C-Left, C-Right
set -g terminal-overrides "rxvt*:XT:smcup@:rmcup@:kUP5=\eOA:kDN5=\eOB:kLFT5=\eOD:kRIT5=\eOC"
